# Generated by Django 5.2.12 on 2026-03-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hizmat turi nomi')),
                ('price', models.IntegerField(help_text="Hizmat turi narxini kiriting! Agar usta haqqi bo'lsa 1m² uchun narxni kiriting", verbose_name='Hizmat turi narxi')),
            ],
            options={
                'verbose_name': 'Hizmat turi nomi',
                'verbose_name_plural': 'Hizmat turlari',
            },
        ),
    ]
