# Generated by Django 5.2.12 on 2026-03-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhesive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kley nomi/turi')),
                ('price', models.PositiveIntegerField(help_text='1 dona kley narxi', verbose_name="Narx (so'm/dona)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Germetik',
                'verbose_name_plural': 'Germetiklar',
            },
        ),
        migrations.CreateModel(
            name='Fasteners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('dimensions', models.CharField(max_length=255, verbose_name="O'lchami")),
                ('price', models.PositiveIntegerField(verbose_name='Narx')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Yordamchi mahsulotlar',
                'verbose_name_plural': 'Yordamchi mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Screw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.IntegerField(help_text="Shurup o'lchami, masalan: 3, 5 | Faqat namunadagidek kiritilishi lozim!", verbose_name="O'lchami")),
                ('price', models.PositiveIntegerField(help_text='1 kg shurup narxi', verbose_name="Narx (so'm/kg)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Shurup',
                'verbose_name_plural': 'Shuruplar',
            },
        ),
    ]
