# Generated by Django 5.2.12 on 2026-03-30 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ko'rsatiladigan to'liq nom, masalan: Xitoy, Rossiya", max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(help_text='URL uchun: china, russia, korea, kazakhstan', unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Ishlab chiqaruvchi',
                'verbose_name_plural': 'Ishlab chiqaruvchilar',
            },
        ),
        migrations.CreateModel(
            name='ProfnastilColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Qizil, Ko‘k, Yashil', max_length=50, verbose_name='Rang nomi')),
                ('slug', models.SlugField(help_text='Masalan: red, blue, green', unique=True, verbose_name='Slug')),
                ('image', models.ImageField(help_text='Rang preview rasmi', upload_to='profnastil/colors/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Profnastil rangi',
                'verbose_name_plural': 'Profnastil ranglari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfnastilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Turi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Profnastil turi',
                'verbose_name_plural': 'Profnastil turlari',
            },
        ),
        migrations.CreateModel(
            name='RoofType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tom turi',
                'verbose_name_plural': 'Tom turlari',
            },
        ),
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Masalan: 0.35, 0.40, 0.50', max_length=10, unique=True, verbose_name='Qalinlik (mm)')),
            ],
            options={
                'verbose_name': 'Qalinlik',
                'verbose_name_plural': 'Qalinliklar',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='CountryProfnastil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_m2', models.PositiveIntegerField(help_text='1 m² profnastil narxi', verbose_name="Narx (so'm/m²)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profnastil_prices', to='roofing.country', verbose_name='Davlat')),
                ('prof_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roofing.profnastiltype', verbose_name='Profnastil turi')),
                ('thickness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roofing.thickness', verbose_name='Qalinlik')),
            ],
            options={
                'verbose_name': 'Davlat narxi',
                'verbose_name_plural': 'Davlat narxlari',
                'ordering': ['country', 'thickness'],
                'constraints': [models.UniqueConstraint(fields=('country', 'thickness', 'prof_type'), name='unique_country_thickness_type')],
            },
        ),
    ]
