# Generated by Django 5.2.12 on 2026-03-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(help_text='Lapsha uzunligi, masalan: 4, 6 metr. Faqat raqam kiritilishi lozim!', verbose_name='Uzunligi')),
                ('dimensions', models.CharField(help_text="Lapsha o'lchami, masalan: 9*21 | Faqat namunadagidek kiritilishi lozim!", max_length=20, verbose_name="O'lchami")),
                ('price_per_m2', models.PositiveIntegerField(help_text='1 m² lapsha narxi', verbose_name="Narx (so'm/m²)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Lapsha',
                'verbose_name_plural': 'Lapshalar',
            },
        ),
        migrations.CreateModel(
            name='Brace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(help_text="Qo'l uzunligi, masalan: 4, 6 metr. Faqat raqam kiritilishi lozim!", verbose_name='Uzunligi')),
                ('dimensions', models.CharField(help_text="Qo'l o'lchami, masalan: 16*5 | Faqat namunadagidek kiritilishi lozim!", max_length=20, verbose_name="O'lchami")),
                ('price_per_m2', models.PositiveIntegerField(help_text="1 m² qo'l narxi", verbose_name="Narx (so'm/m²)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': "Qo'l",
                'verbose_name_plural': "Qo'llar",
            },
        ),
        migrations.CreateModel(
            name='PostColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_type', models.CharField(help_text='Ustun turini kiriting, masalan, terak, profil', max_length=255, verbose_name='Ustun turi')),
                ('length', models.IntegerField(help_text='Ustun uzunligi, masalan: 4, 6 metr. Faqat raqam kiritilishi lozim!', verbose_name='Uzunligi')),
                ('dimensions', models.CharField(help_text="Ustun o'lchami, masalan: 16*5 | Faqat namunadagidek kiritilishi lozim!", max_length=20, verbose_name="O'lchami")),
                ('price_per_m2', models.PositiveIntegerField(help_text='1 m² ustun narxi', verbose_name="Narx (so'm/m²)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Ustun',
                'verbose_name_plural': 'Ustunlar',
            },
        ),
        migrations.CreateModel(
            name='Purlin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(help_text='Sarrob uzunligi, masalan: 4, 6 metr. Faqat raqam kiritilishi lozim!', verbose_name='Uzunligi')),
                ('dimensions', models.CharField(help_text="Sarrob o'lchami, masalan: 16*5 | Faqat namunadagidek kiritilishi lozim!", max_length=20, verbose_name="O'lchami")),
                ('price_per_m2', models.PositiveIntegerField(help_text='1 m² sarrob narxi', verbose_name="Narx (so'm/m²)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Sarrob',
                'verbose_name_plural': 'Sarroblar',
            },
        ),
        migrations.CreateModel(
            name='Rafter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(help_text='Stropila uzunligi, masalan: 4, 6 metr. Faqat raqam kiritilishi lozim!', verbose_name='Uzunligi')),
                ('dimensions', models.CharField(help_text="Stropila o'lchami, masalan: 11.35, 14.35 | Faqat namunadagidek kiritilishi lozim!", max_length=20, verbose_name="O'lchami")),
                ('price_per_m2', models.PositiveIntegerField(help_text='1 m² stropila narxi', verbose_name="Narx (so'm/m²)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Stropila',
                'verbose_name_plural': 'Stropilalar',
            },
        ),
    ]
